apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: app
data:
  DB_WRITER_HOST: "soundcloud-prod-postgres.cf42qiw2429n.ap-northeast-2.rds.amazonaws.com"
  DB_READER_HOST: "soundcloud-prod-postgres.cf42qiw2429n.ap-northeast-2.rds.amazonaws.com"
  DB_USER: "postgres"
  DB_NAME: "worldcup"
  DB_PORT: "5432"