# [Values] LB Controller — clusterName/IRSA ARN <- terraform outputs에서 복사
clusterName: soundcloud-prod-eks
region: ap-northeast-2
vpcId: vpc-05c5d0f8e55406fa8

replicaCount: 1

nodeSelector:
  role: system

configureDefaultAffinity: false
topologySpreadConstraints: []

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::201243087060:role/soundcloud-prod-lb-controller
