# [Values] LB Controller — clusterName/IRSA ARN <- terraform outputs에서 복사
clusterName: soundcloud-prod-eks
region: ap-northeast-2
vpcId: vpc-03d877a2382472a2e

replicaCount: 2

nodeSelector:
  role: system

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::201243087060:role/soundcloud-prod-lb-controller