# [Values] Karpenter 헬름 차트 설정
settings:
  clusterName: soundcloud-prod-eks                  
  interruptionQueue: soundcloud-prod-eks          

serviceAccount:
  annotations:
    # <- output: karpenter_controller_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::201243087060:role/soundcloud-prod-eks-karpenter-controller

nodeSelector:
  role: system

replicas: 2

controller:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
