operator:
  replicaCount: 1
  nodeSelector:
    role: system
  topologySpreadConstraints: []

metricsServer:
  replicaCount: 1
  nodeSelector:
    role: system
  topologySpreadConstraints: []

webhooks:
  replicaCount: 1
  nodeSelector:
    role: system
  topologySpreadConstraints: []

watchNamespace: ""

podDisruptionBudget:
  operator:
    maxUnavailable: 1
  metricServer:
    maxUnavailable: 1

prometheus:
  metricServer:
    enabled: true
