global:
  clusterId: "soundcloud-prod-eks"
  prometheus:
    enabled: false
    fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
  grafana:
    enabled: false
    proxy: false
  federatedStorage:
    config: |-
      type: S3
      config:
        bucket: project-sc-cost
        region: ap-northeast-2
        endpoint: s3.ap-northeast-2.amazonaws.com


prometheus:
  server:
    global:
      external_labels:
        cluster_id: "soundcloud-prod-eks"

kubecostProductConfigs:
  clusterName: "soundcloud-prod-eks"

serviceAccount:
  create: true
  name: "kubecost-cost-analyzer"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::201243087060:role/soundcloud-prod-eks-kubecost

nodeSelector:
  role: system

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
  aggregatorMetrics:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
persistentVolume:
  size: 32Gi
  enabled: true
  storageClass: "efs-sc"

finopsagent:
  enabled: true
  persistence:
    storageClass: "efs-sc"
    accessModes:
      - ReadWriteMany
    size: 8Gi
