grafana:
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: ClusterIP
  nodeSelector:
    role: system
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 45d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
    nodeSelector:
      role: system
  service:
    type: ClusterIP

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: system

kube-state-metrics:
  nodeSelector:
    role: system
  metricLabelsAllowlist:
    - nodes=[karpenter.sh/nodepool,karpenter.sh/capacity-type]

prometheusOperator:
  nodeSelector:
    role: system

prometheus-node-exporter:
  tolerations:
    - operator: Exists