serviceMonitor:
  enabled: true
  namespace: monitoring
  additionalLabels:
    release: kube-prometheus-stack

nodeSelector:
  role: system

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi