apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-02b674f985d1e0a06 # terraform output efs_prophet_file_system_id 값으로 교체
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/prophet"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer