apiVersion: v1
kind: Service
metadata:
  name: yace
  namespace: monitoring
  labels:
    app: yace
spec:
  selector:
    app: yace
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000