apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuralprophet-model
  namespace: ai
  labels:
    app: neuralprophet
    component: train
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi