apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubecost.github.io/cost-analyzer
      chart: cost-analyzer
      targetRevision: 2.9.6
      helm:
        valueFiles:
          - $values/k8s/values/kubecost-values.yaml
    - repoURL: https://github.com/soundcloud-yaho/infra.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true