# [App] kube-prometheus-stack (Prometheus/Grafana) + Pushgateway
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 87.10.1
      helm:
        valueFiles:
          - $values/k8s/values/monitoring-values.yaml
    - repoURL: https://github.com/soundcloud-yaho/infra.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
